### ISSUE TITLE
IDL error: variant or record tag out of order

### ISSUE THREAD

**Issue by tomijaga** [Gekctek/motoko_candid#2]
Hey @Gekctek, I want to report an error that occurs when encoding nested objects or arrays.

I might be entering the data incorrectly, so I reproduced the error here:
[Motoko playground](https://m7sm4-2iaaa-aaaab-qabra-cai.raw.ic0.app/?tag=3421962934)

**Comment by Gekctek** [comment]
@tomijaga try candid 0.1.1 on MOPS

**Comment by tomijaga** [comment]
I tried the new version, and it works well now. 🙌
